name: api rust doc

on:
  push:
    branches: [ "steve/issue_6-api_documentation_v2_test" ]
  pull_request:
    branches: [ "main" ]

permissions: {}
jobs:
  deploy:
    permissions:
      contents: write # to push pages branch (peaceiris/actions-gh-pages)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build api rust doc
        run: cargo doc --no-deps --package chiquito

      - name: Add index.html file to docs root
        run: |
          mkdir -p ./target/doc
          echo '<meta http-equiv="refresh" content="0; url=chiquito">' > ./target/doc/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          destination_dir: ./docs